
version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "topfan-lite-dev"
s3_bucket = "dev-pipeline-topfan-lite"
s3_prefix = "dev-pipeline-topfan-lite"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
image_repositories = []
parameter_overrides = "StageName=\"Prod\""
